# -*- coding: utf-8 -*-

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_PurchaseDialog:
    def setupUi(self, PurchaseDialog):
        PurchaseDialog.setObjectName("PurchaseDialog")
        PurchaseDialog.resize(300, 300)
        PurchaseDialog.setMinimumSize(QtCore.QSize(300, 300))
        PurchaseDialog.setMaximumSize(QtCore.QSize(300, 300))
        self.gridLayout = QtWidgets.QGridLayout(PurchaseDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.back_frame = QtWidgets.QFrame(PurchaseDialog)
        self.back_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.back_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.back_frame.setObjectName("back_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.back_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.book_id_frame = QtWidgets.QFrame(self.back_frame)
        self.book_id_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.book_id_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.book_id_frame.setObjectName("book_id_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.book_id_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.book_id_Label = QtWidgets.QLabel(self.book_id_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.book_id_Label.setFont(font)
        self.book_id_Label.setObjectName("book_id_Label")
        self.horizontalLayout.addWidget(self.book_id_Label)
        self.book_id_LE = QtWidgets.QLineEdit(self.book_id_frame)
        self.book_id_LE.setObjectName("book_id_LE")
        self.horizontalLayout.addWidget(self.book_id_LE)
        self.gridLayout_2.addWidget(self.book_id_frame, 0, 0, 1, 1)
        self.quantity_frame = QtWidgets.QFrame(self.back_frame)
        self.quantity_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quantity_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quantity_frame.setObjectName("quantity_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.quantity_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.quantity_Label = QtWidgets.QLabel(self.quantity_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.quantity_Label.setFont(font)
        self.quantity_Label.setObjectName("quantity_Label")
        self.horizontalLayout_2.addWidget(self.quantity_Label)
        self.quantity_SB = QtWidgets.QSpinBox(self.quantity_frame)
        self.quantity_SB.setMinimum(1)
        self.quantity_SB.setMaximum(990)
        self.quantity_SB.setObjectName("quantity_SB")
        self.horizontalLayout_2.addWidget(self.quantity_SB)
        self.gridLayout_2.addWidget(self.quantity_frame, 1, 0, 1, 1)
        self.submit_frame = QtWidgets.QFrame(self.back_frame)
        self.submit_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.submit_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.submit_frame.setObjectName("submit_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.submit_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.submit_Btn = QtWidgets.QPushButton(self.submit_frame)
        self.submit_Btn.setObjectName("submit_Btn")
        self.gridLayout_3.addWidget(self.submit_Btn, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.submit_frame, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.back_frame, 2, 0, 1, 1)

        self.retranslateUi(PurchaseDialog)
        QtCore.QMetaObject.connectSlotsByName(PurchaseDialog)

    def retranslateUi(self, PurchaseDialog):
        PurchaseDialog.setWindowTitle(QtWidgets.QApplication.translate("PurchaseDialog", "Purchase", None, -1))
        self.book_id_Label.setText(QtWidgets.QApplication.translate("PurchaseDialog", "Book ID:", None, -1))
        self.quantity_Label.setText(QtWidgets.QApplication.translate("PurchaseDialog", "Quantity:", None, -1))
        self.submit_Btn.setText(QtWidgets.QApplication.translate("PurchaseDialog", "Submit", None, -1))

