# -*- coding: utf-8 -*-

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_StatisticDialog:
    def setupUi(self, StatisticDialog):
        StatisticDialog.setObjectName("StatisticDialog")
        StatisticDialog.resize(1000, 800)
        StatisticDialog.setMinimumSize(QtCore.QSize(1000, 800))
        StatisticDialog.setMaximumSize(QtCore.QSize(1000, 800))
        self.horizontalLayout = QtWidgets.QHBoxLayout(StatisticDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_frame = QtWidgets.QFrame(StatisticDialog)
        self.back_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.back_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.back_frame.setObjectName("back_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.back_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.sales_frame = QtWidgets.QFrame(self.back_frame)
        self.sales_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sales_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sales_frame.setObjectName("sales_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.sales_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.sales_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.sales_LE = QtWidgets.QLineEdit(self.sales_frame)
        self.sales_LE.setReadOnly(True)
        self.sales_LE.setObjectName("sales_LE")
        self.horizontalLayout_3.addWidget(self.sales_LE)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.gridLayout.addWidget(self.sales_frame, 5, 0, 1, 1)
        self.date_frame = QtWidgets.QFrame(self.back_frame)
        self.date_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.date_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.date_frame.setObjectName("date_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.date_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.date_Label = QtWidgets.QLabel(self.date_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.date_Label.setFont(font)
        self.date_Label.setObjectName("date_Label")
        self.horizontalLayout_2.addWidget(self.date_Label)
        self.date_edit = QtWidgets.QDateEdit(self.date_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.date_edit.setFont(font)
        self.date_edit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.date_edit.setObjectName("date_edit")
        self.horizontalLayout_2.addWidget(self.date_edit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.gridLayout.addWidget(self.date_frame, 1, 0, 1, 2)
        self.submit_frame = QtWidgets.QFrame(self.back_frame)
        self.submit_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.submit_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.submit_frame.setObjectName("submit_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.submit_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.submit_Btn = QtWidgets.QPushButton(self.submit_frame)
        self.submit_Btn.setObjectName("submit_Btn")
        self.gridLayout_3.addWidget(self.submit_Btn, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.submit_frame, 2, 0, 3, 2)
        self.ranking_frame = QtWidgets.QFrame(self.back_frame)
        self.ranking_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ranking_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ranking_frame.setObjectName("ranking_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ranking_frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ranking_Label = QtWidgets.QLabel(self.ranking_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ranking_Label.setFont(font)
        self.ranking_Label.setObjectName("ranking_Label")
        self.gridLayout_5.addWidget(self.ranking_Label, 1, 0, 1, 1)
        self.ranking_table = QtWidgets.QTableWidget(self.ranking_frame)
        self.ranking_table.setObjectName("ranking_table")
        self.ranking_table.setColumnCount(3)
        self.ranking_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ranking_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ranking_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ranking_table.setHorizontalHeaderItem(2, item)
        self.gridLayout_5.addWidget(self.ranking_table, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.ranking_frame, 7, 0, 1, 2)
        self.quantity_frame = QtWidgets.QFrame(self.back_frame)
        self.quantity_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quantity_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quantity_frame.setObjectName("quantity_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.quantity_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.quantity_Label = QtWidgets.QLabel(self.quantity_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.quantity_Label.setFont(font)
        self.quantity_Label.setObjectName("quantity_Label")
        self.horizontalLayout_4.addWidget(self.quantity_Label)
        self.quantity_LE = QtWidgets.QLineEdit(self.quantity_frame)
        self.quantity_LE.setReadOnly(True)
        self.quantity_LE.setObjectName("quantity_LE")
        self.horizontalLayout_4.addWidget(self.quantity_LE)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.gridLayout.addWidget(self.quantity_frame, 6, 0, 1, 1)
        self.horizontalLayout.addWidget(self.back_frame)

        self.retranslateUi(StatisticDialog)
        QtCore.QMetaObject.connectSlotsByName(StatisticDialog)

    def retranslateUi(self, StatisticDialog):
        StatisticDialog.setWindowTitle(QtWidgets.QApplication.translate("StatisticDialog", "Statistic", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("StatisticDialog", "Total Sales:", None, -1))
        self.date_Label.setText(QtWidgets.QApplication.translate("StatisticDialog", "Year / Month", None, -1))
        self.date_edit.setDisplayFormat(QtWidgets.QApplication.translate("StatisticDialog", "yyyy/M", None, -1))
        self.submit_Btn.setText(QtWidgets.QApplication.translate("StatisticDialog", "Submit", None, -1))
        self.ranking_Label.setText(QtWidgets.QApplication.translate("StatisticDialog", "Ranking:", None, -1))
        self.ranking_table.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("StatisticDialog", "Title", None, -1))
        self.ranking_table.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("StatisticDialog", "Author", None, -1))
        self.ranking_table.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("StatisticDialog", "Sales", None, -1))
        self.quantity_Label.setText(QtWidgets.QApplication.translate("StatisticDialog", "Total Quantity:", None, -1))

